# -*- coding: utf-8 -*-
"""IMDB top 250 movies web Scrapping Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iLroIIL3DCWW4l-RmGtLCal9Y01Lrcwu

IMPORTING DEPENDENCIES
"""

from bs4 import BeautifulSoup
import requests, openpyxl

excel = openpyxl.Workbook()
sheet = excel.active
sheet.title = 'Top Rated Movies '
print(excel.sheetnames)
sheet.append(['Movie Rank', 'Movie Name','Year','Rating'])

try: 
  source = requests.get('https://www.imdb.com/chart/top/')

  #raise foe status is used for error check in the url
  source.raise_for_status()
  htmldata = BeautifulSoup(source.text, 'html.parser')
  movies  = htmldata.find('tbody',class_='lister-list').find_all('tr')
  #iterating web data  
  for movie in movies:
    name = movie.find('td',class_ = 'titleColumn').a.text
    rank = movie.find('td',class_ = 'titleColumn').get_text(strip=True).split('.')[0]
    rating = movie.find('td',class_ = 'ratingColumn imdbRating').get_text(strip=True)
    year = movie.find('td',class_ = 'titleColumn').span.text.strip('()')

    #appending scraped data into excel file
    sheet.append([rank,name,year,rating])

except Exception as e:
  print(e)

#saving excel data
excel.save('IMDB Movie Ratings.xlsx')

